alias pm='python manage.py'
alias makemigrations='python manage.py makemigrations'
alias migrate='python manage.py migrate'
alias runserver='python manage.py runserver'
alias showmigrations='python manage.py showmigrations'