# Generated by Django 4.2.4 on 2023-08-05 05:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.IntegerField()),
                ("activo", models.BooleanField(default=True)),
                (
                    "fecha_de_creacion",
                    models.DateField(default=datetime.date(2023, 8, 4)),
                ),
            ],
            options={
                "verbose_name": "estatus",
                "verbose_name_plural": "estatuses",
            },
        ),
        migrations.CreateModel(
            name="TipoDeSolicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.CharField(max_length=500)),
                ("activo", models.BooleanField(default=True)),
                (
                    "fecha_de_creacion",
                    models.DateField(default=datetime.date(2023, 8, 4)),
                ),
            ],
            options={
                "verbose_name": "tipo_de_solicitud",
                "verbose_name_plural": "tipos_de_solicitud",
            },
        ),
        migrations.CreateModel(
            name="Solicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "fecha_de_creacion",
                    models.DateField(default=datetime.date(2023, 8, 4)),
                ),
                (
                    "tipo_solicitud",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="solicitudes.tipodesolicitud",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "solicitud",
                "verbose_name_plural": "solicitudes",
            },
        ),
        migrations.CreateModel(
            name="Reporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "fecha_de_creacion",
                    models.DateField(default=datetime.date(2023, 8, 4)),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solicitudes.solicitud",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistorialDeSolicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "fecha_de_creacion",
                    models.DateField(default=datetime.date(2023, 8, 4)),
                ),
                (
                    "estatus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solicitudes.estatus",
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solicitudes.solicitud",
                    ),
                ),
            ],
            options={
                "verbose_name": "historial_de_solicitud",
                "verbose_name_plural": "historial_de_solicitudes",
            },
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=500)),
                ("activo", models.BooleanField(default=True)),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solicitudes.solicitud",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.usuario",
                    ),
                ),
            ],
        ),
    ]
