# Generated by Django 4.2.4 on 2023-08-03 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TiposDeUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=20)),
                ("activo", models.BooleanField()),
                ("fecha_de_registro", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=20)),
                ("segundo_nombre", models.CharField()),
                ("apellido", models.CharField()),
                ("segundo_apellido", models.CharField()),
                ("fecha_de_nacimiento", models.DateField()),
                ("activo", models.BooleanField()),
                ("fecha_de_registro", models.DateField()),
                (
                    "tipo_de_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solicitudes.tiposdeusuario",
                    ),
                ),
            ],
        ),
    ]
