# Generated by Django 4.2.4 on 2023-08-08 01:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usuarios", "0003_alter_tipodeusuario_fecha_de_creacion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "fecha_de_creacion",
                    models.DateField(default=datetime.date(2023, 8, 7)),
                ),
            ],
            options={
                "verbose_name_plural": "acciones",
            },
        ),
        migrations.CreateModel(
            name="Espacio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "fecha_de_creacion",
                    models.DateField(default=datetime.date(2023, 8, 7)),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Estatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(unique=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "fecha_de_creacion",
                    models.DateField(default=datetime.date(2023, 8, 7)),
                ),
            ],
            options={
                "verbose_name": "estatus",
                "verbose_name_plural": "estatuses",
            },
        ),
        migrations.CreateModel(
            name="Prioridad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "fecha_de_creacion",
                    models.DateField(default=datetime.date(2023, 8, 7)),
                ),
            ],
            options={
                "verbose_name_plural": "prioridades",
            },
        ),
        migrations.CreateModel(
            name="Solicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("informacion_adicional", models.CharField(max_length=500)),
                ("direccion", models.CharField(max_length=200)),
                ("estado", models.CharField(max_length=50)),
                ("municipio_ciudad", models.CharField(max_length=50)),
                ("codigo_postal", models.IntegerField(max_length=10)),
                ("activo", models.BooleanField(default=True)),
                (
                    "fecha_de_creacion",
                    models.DateField(default=datetime.date(2023, 8, 7)),
                ),
                (
                    "accion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="solicitudes.accion",
                    ),
                ),
                (
                    "espacio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="solicitudes.espacio",
                    ),
                ),
                (
                    "prioridad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solicitudes.prioridad",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "solicitud",
                "verbose_name_plural": "solicitudes",
            },
        ),
        migrations.CreateModel(
            name="Reporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "fecha_de_creacion",
                    models.DateField(default=datetime.date(2023, 8, 7)),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solicitudes.solicitud",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistorialDeSolicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "fecha_de_creacion",
                    models.DateField(default=datetime.date(2023, 8, 7)),
                ),
                (
                    "estatus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solicitudes.estatus",
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solicitudes.solicitud",
                    ),
                ),
            ],
            options={
                "verbose_name": "historial_de_solicitud",
                "verbose_name_plural": "historial_de_solicitudes",
            },
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=500)),
                ("activo", models.BooleanField(default=True)),
                (
                    "fecha_de_creacion",
                    models.DateField(default=datetime.date(2023, 8, 7)),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solicitudes.solicitud",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.usuario",
                    ),
                ),
            ],
        ),
    ]
