# Generated by Django 4.2.4 on 2023-08-03 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("solicitudes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tiposdeusuario",
            options={"verbose_name": "tipos de usuario"},
        ),
        migrations.AlterModelOptions(
            name="usuarios",
            options={"verbose_name": "usuarios"},
        ),
    ]
