# Generated by Django 4.2.4 on 2023-08-04 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("solicitudes", "0002_alter_tiposdeusuario_options_alter_usuarios_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=500)),
                ("activo", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Estatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.IntegerField()),
                ("activo", models.BooleanField()),
                ("fecha_de_registro", models.DateField()),
            ],
            options={
                "verbose_name_plural": "Estatuses",
            },
        ),
        migrations.CreateModel(
            name="HistorialDeSolicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField()),
                ("fecha_de_creacion", models.DateField()),
                (
                    "estatus_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solicitudes.estatus",
                    ),
                ),
            ],
            options={
                "verbose_name": "historial_de_solicitud",
                "verbose_name_plural": "historial_de_solicitudes",
            },
        ),
        migrations.CreateModel(
            name="Reporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField()),
                ("fecha_de_creacion", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Solicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField()),
                ("fecha_de_creacion", models.DateField()),
            ],
            options={
                "verbose_name_plural": "solicitudes",
            },
        ),
        migrations.CreateModel(
            name="TipoDeSolicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.CharField(max_length=500)),
                ("activo", models.BooleanField()),
                ("fecha_de_creacion", models.DateField()),
            ],
            options={
                "verbose_name": "tipo_de_solicitud",
                "verbose_name_plural": "tipos_de_solicitud",
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("segundo_nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("segundo_apellido", models.CharField(max_length=50)),
                ("fecha_de_nacimiento", models.DateField()),
                ("activo", models.BooleanField()),
                ("fecha_de_creacion", models.DateField()),
            ],
            options={
                "verbose_name": "usuarios",
            },
        ),
        migrations.RenameField(
            model_name="tiposdeusuario",
            old_name="fecha_de_registro",
            new_name="fecha_de_creacion",
        ),
        migrations.DeleteModel(
            name="Usuarios",
        ),
        migrations.AddField(
            model_name="usuario",
            name="tipo_de_usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="solicitudes.tiposdeusuario",
            ),
        ),
        migrations.AddField(
            model_name="solicitud",
            name="tipo_solicitud_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="solicitudes.tipodesolicitud",
            ),
        ),
        migrations.AddField(
            model_name="solicitud",
            name="usuario_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="solicitudes.usuario"
            ),
        ),
        migrations.AddField(
            model_name="reporte",
            name="solicitud_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="solicitudes.solicitud"
            ),
        ),
        migrations.AddField(
            model_name="reporte",
            name="usuario_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="solicitudes.usuario"
            ),
        ),
        migrations.AddField(
            model_name="historialdesolicitud",
            name="solicitud_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="solicitudes.solicitud"
            ),
        ),
        migrations.AddField(
            model_name="comentario",
            name="solicitud_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="solicitudes.solicitud"
            ),
        ),
        migrations.AddField(
            model_name="comentario",
            name="usuario_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="solicitudes.usuario"
            ),
        ),
    ]
