# Generated by Django 4.2.4 on 2023-08-17 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solicitudes", "0002_alter_solicitud_codigo_postal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accion",
            name="fecha_de_creacion",
            field=models.DateField(default=datetime.date(2023, 8, 16)),
        ),
        migrations.AlterField(
            model_name="comentario",
            name="fecha_de_creacion",
            field=models.DateField(default=datetime.date(2023, 8, 16)),
        ),
        migrations.AlterField(
            model_name="espacio",
            name="fecha_de_creacion",
            field=models.DateField(default=datetime.date(2023, 8, 16)),
        ),
        migrations.AlterField(
            model_name="estatus",
            name="fecha_de_creacion",
            field=models.DateField(default=datetime.date(2023, 8, 16)),
        ),
        migrations.AlterField(
            model_name="historialdesolicitud",
            name="fecha_de_creacion",
            field=models.DateField(default=datetime.date(2023, 8, 16)),
        ),
        migrations.AlterField(
            model_name="prioridad",
            name="fecha_de_creacion",
            field=models.DateField(default=datetime.date(2023, 8, 16)),
        ),
        migrations.AlterField(
            model_name="reporte",
            name="fecha_de_creacion",
            field=models.DateField(default=datetime.date(2023, 8, 16)),
        ),
        migrations.AlterField(
            model_name="solicitud",
            name="fecha_de_creacion",
            field=models.DateField(default=datetime.date(2023, 8, 16)),
        ),
    ]
