# Generated by Django 4.2.4 on 2023-08-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solicitudes", "0004_alter_usuario_tipo_de_usuario"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="estatus",
            options={"verbose_name": "estatus", "verbose_name_plural": "estatuses"},
        ),
        migrations.AlterModelOptions(
            name="solicitud",
            options={"verbose_name": "solicitud", "verbose_name_plural": "solicitudes"},
        ),
        migrations.AlterModelOptions(
            name="tiposdeusuario",
            options={"verbose_name": "tipos_de_usuario"},
        ),
        migrations.AlterModelOptions(
            name="usuario",
            options={"verbose_name_plural": "usuarios"},
        ),
        migrations.RenameField(
            model_name="comentario",
            old_name="solicitud_id",
            new_name="solicitud",
        ),
        migrations.RenameField(
            model_name="comentario",
            old_name="usuario_id",
            new_name="usuario",
        ),
        migrations.RenameField(
            model_name="historialdesolicitud",
            old_name="estatus_id",
            new_name="estatus",
        ),
        migrations.RenameField(
            model_name="historialdesolicitud",
            old_name="solicitud_id",
            new_name="solicitud",
        ),
        migrations.RenameField(
            model_name="reporte",
            old_name="solicitud_id",
            new_name="solicitud",
        ),
        migrations.RenameField(
            model_name="reporte",
            old_name="usuario_id",
            new_name="usuario",
        ),
        migrations.RenameField(
            model_name="solicitud",
            old_name="tipo_solicitud_id",
            new_name="tipo_solicitud",
        ),
        migrations.RenameField(
            model_name="solicitud",
            old_name="usuario_id",
            new_name="usuario",
        ),
        migrations.AddField(
            model_name="usuario",
            name="contrasena",
            field=models.CharField(default="missing_password"),
        ),
        migrations.AddField(
            model_name="usuario",
            name="correo_electronico",
            field=models.CharField(default="missing_email", max_length=100),
        ),
        migrations.AlterField(
            model_name="comentario",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="estatus",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="historialdesolicitud",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="reporte",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="solicitud",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="tipodesolicitud",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="tiposdeusuario",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="activo",
            field=models.BooleanField(default=True),
        ),
    ]
