# Generated by Django 4.2.4 on 2023-08-19 23:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("solicitudes", "0004_alter_accion_fecha_de_creacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="estatus",
            name="descripcion",
            field=models.CharField(default="Missing descripcion", max_length=100),
        ),
        migrations.AlterField(
            model_name="accion",
            name="fecha_de_creacion",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="comentario",
            name="fecha_de_creacion",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="espacio",
            name="fecha_de_creacion",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="estatus",
            name="fecha_de_creacion",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="historialdesolicitud",
            name="fecha_de_creacion",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="prioridad",
            name="fecha_de_creacion",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="reporte",
            name="fecha_de_creacion",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="solicitud",
            name="fecha_de_creacion",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
