# Generated by Django 4.2.4 on 2023-08-04 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solicitudes", "0005_alter_estatus_options_alter_solicitud_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estatus",
            name="fecha_de_registro",
            field=models.DateField(default=datetime.date(2023, 8, 4)),
        ),
        migrations.AlterField(
            model_name="historialdesolicitud",
            name="fecha_de_creacion",
            field=models.DateField(default=datetime.date(2023, 8, 4)),
        ),
        migrations.AlterField(
            model_name="reporte",
            name="fecha_de_creacion",
            field=models.DateField(default=datetime.date(2023, 8, 4)),
        ),
        migrations.AlterField(
            model_name="solicitud",
            name="fecha_de_creacion",
            field=models.DateField(default=datetime.date(2023, 8, 4)),
        ),
        migrations.AlterField(
            model_name="tipodesolicitud",
            name="fecha_de_creacion",
            field=models.DateField(default=datetime.date(2023, 8, 4)),
        ),
        migrations.AlterField(
            model_name="tiposdeusuario",
            name="fecha_de_creacion",
            field=models.DateField(default=datetime.date(2023, 8, 4)),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="fecha_de_creacion",
            field=models.DateField(default=datetime.date(2023, 8, 4)),
        ),
    ]
