# Generated by Django 4.2.4 on 2023-08-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "solicitudes",
            "0005_estatus_descripcion_alter_accion_fecha_de_creacion_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="estatus",
            name="descripcion",
            field=models.CharField(default="Missing descripcion", max_length=200),
        ),
    ]
