# Generated by Django 4.2.4 on 2023-08-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("solicitudes", "0006_alter_estatus_fecha_de_registro_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="estatus",
            old_name="fecha_de_registro",
            new_name="fecha_de_creacion",
        ),
    ]
