# Generated by Django 4.2.4 on 2023-08-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solicitudes", "0007_rename_fecha_de_registro_estatus_fecha_de_creacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="segundo_nombre",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
