# Generated by Django 4.2.4 on 2023-08-08 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_alter_tipodeusuario_fecha_de_creacion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tipodeusuario",
            name="fecha_de_creacion",
            field=models.DateField(default=datetime.date(2023, 8, 7)),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="fecha_de_creacion",
            field=models.DateField(default=datetime.date(2023, 8, 7)),
        ),
    ]
