# Generated by Django 4.2.4 on 2023-08-17 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_alter_tipodeusuario_fecha_de_creacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="ciudad_municipio",
            field=models.CharField(default="missing_ciudad_municipio", max_length=50),
        ),
        migrations.AddField(
            model_name="usuario",
            name="estado",
            field=models.CharField(default="missing_estado", max_length=50),
        ),
        migrations.AlterField(
            model_name="tipodeusuario",
            name="fecha_de_creacion",
            field=models.DateField(default=datetime.date(2023, 8, 16)),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="fecha_de_creacion",
            field=models.DateField(default=datetime.date(2023, 8, 16)),
        ),
    ]
