# Generated by Django 4.2.4 on 2023-08-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0004_usuario_ciudad_municipio_usuario_estado_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="ciudad_municipio",
        ),
        migrations.AddField(
            model_name="usuario",
            name="municipio_ciudad",
            field=models.CharField(default="missing_municipio_ciudad", max_length=50),
        ),
    ]
