# Generated by Django 4.2.4 on 2023-08-19 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0005_remove_usuario_ciudad_municipio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tipodeusuario",
            name="fecha_de_creacion",
            field=models.DateTimeField(default=datetime.date(2023, 8, 19)),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="fecha_de_creacion",
            field=models.DateTimeField(default=datetime.date(2023, 8, 19)),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="fecha_de_nacimiento",
            field=models.DateTimeField(),
        ),
    ]
