# Generated by Django 4.2.4 on 2023-08-19 23:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0006_alter_tipodeusuario_fecha_de_creacion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tipodeusuario",
            name="fecha_de_creacion",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="fecha_de_creacion",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
